#!/usr/bin/env python3
"""Real Linux backend/launcher integration; no mocked executables.

Uses the known-shift fixtures generated by backends/mt/test/test_modes.py.
Numerical references are run directly; every routed call must retain its
backend's output. Stock -nointerp offsets have a known undefined-fraction bug.
"""
import argparse,hashlib,json,os,pathlib,resource,shlex,subprocess,time,sys
import numpy as np

p=argparse.ArgumentParser(description=__doc__)
p.add_argument('--prefix',type=pathlib.Path,required=True)
p.add_argument('--original',type=pathlib.Path,required=True)
p.add_argument('--fixtures',type=pathlib.Path,required=True)
p.add_argument('--work',type=pathlib.Path,required=True)
p.add_argument('--phase',choices=['all','modes','workflows'],default='all')
a=p.parse_args();root=a.work.resolve();root.mkdir(parents=True,exist_ok=True)
entry=a.prefix.resolve()/'bin/xcorr3'
executables={'original':a.original.resolve(),'mt':a.prefix.resolve()/'bin/xcorr_mt','cc':a.prefix.resolve()/'bin/xcorr_cc'}
env=dict(os.environ,PATH=str(a.prefix.resolve()/'bin')+':'+os.environ['PATH'],OPENBLAS_NUM_THREADS='1',CUDA_CACHE_DISABLE='1')
env.pop('OMP_NUM_THREADS',None)
env.pop('XCORR3_ACTIVE',None)
base=['-nx','7','-ny','5','-xsearch','32','-ysearch','32']
records=[]
sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()

def run(tag,backend='original',mode='direct',options=(),inputs=('master.PRM','aligned.PRM'),
        expected=None,workers=None,error=False,limit=None,ignore_failure=False):
    work=root/tag;work.mkdir()
    for f in a.fixtures.resolve().iterdir():
        (work/f.name).symlink_to(f.resolve())
    args=[*inputs,*base,*options]
    out=work/('time_xcorr_Gatelli.dat' if '-time4' in options else 'time_xcorr.dat' if '-time' in options else 'freq_xcorr.dat')
    sentinel=b'previous complete output\n'
    if error:out.write_bytes(sentinel)
    if mode=='direct':cmd=[str(executables[backend]),*args]
    elif mode=='cli':cmd=[str(entry),'--backend',backend,*args]
    else:
        config=work/'user config.txt'
        config.write_text('proc_stage = 1\nxcorr_backend = '+backend+'\nxcorr_nproc = '+str(workers or 'auto')+'\n')
        cmd=[str(entry),'--config',str(config)]
        if mode=='config':cmd+=args
        elif mode=='workflow':
            shell='xcorr '+shlex.join(args)
            # Limit only the intercepted child, after shim creation. Use exact
            # bytes: csh's displayed file-size limits can be rounded upward.
            if limit:
                helper=work/'limit_child.py'
                helper.write_text('import os,resource,sys\nresource.setrlimit(resource.RLIMIT_FSIZE,('+str(limit)+','+str(limit)+'))\nos.execvp("xcorr",["xcorr",*sys.argv[1:]])\n')
                shell=shlex.join([sys.executable,str(helper),*args])
            shell+='; /bin/true' if ignore_failure else '; set result=$status; exit $result'
            cmd+=['--run','csh','-f','-c',shell]
        else:raise ValueError(mode)
    def restrict():resource.setrlimit(resource.RLIMIT_FSIZE,(limit,limit))
    start=time.monotonic()
    done=subprocess.run(cmd,cwd=work,env=env,capture_output=True,timeout=180,preexec_fn=restrict if limit and mode!='workflow' else None)
    (work/'stdout.log').write_bytes(done.stdout);(work/'stderr.log').write_bytes(done.stderr)
    rec=dict(name=tag,backend=backend,mode=mode,returncode=done.returncode,seconds=time.monotonic()-start,command=cmd)
    if error:
        rec['pass']=done.returncode>0 and out.read_bytes()==sentinel
    else:
        rec['pass']=done.returncode==0 and out.exists()
        if rec['pass']:
            data=np.atleast_2d(np.loadtxt(out));rec['rows']=len(data);rec['sha256']=sha(out)
            rec['pass']=len(data)==35 and data.shape[1]==(6 if backend=='cc' else 5)
            if '-nointerp' in options:
                rec['finite']=bool(np.isfinite(data[:,[0,2,4]] if backend=='original' else data).all())
                if backend!='original':rec['pass'] &= bool(np.all(data[:,1]==3) and np.all(data[:,3]==2))
            else:rec['finite']=bool(np.isfinite(data).all())
            rec['pass'] &= rec['finite']
            if expected:
                if backend=='original' and '-nointerp' in options:
                    ref=np.loadtxt(expected)
                    rec['equal']=bool(np.array_equal(data[:,[0,2,4]],ref[:,[0,2,4]]))
                    rec['note']='stock nointerp undefined offset fractions excluded; coordinates/correlation compared'
                else:rec['equal']=out.read_bytes()==expected.read_bytes()
                rec['pass'] &= rec['equal']
    rec['pass']=bool(rec['pass']);records.append(rec)
    (root/'results.json').write_text(json.dumps(dict(passed=all(r['pass'] for r in records),count=len(records),cases=records),indent=2))
    print(('PASS ' if rec['pass'] else 'FAIL ')+tag,flush=True)
    return out

modes=[
    ('frequency',[],('master.PRM','aligned.PRM')),('frequency_explicit',['-freq'],('master.PRM','aligned.PRM')),
    ('time',['-time'],('master.PRM','aligned.PRM')),
    ('time4',['-time4'],('master.PRM','aligned.PRM')),('real',['-real'],('masterF.PRM','alignedF.PRM')),
    ('grid',[],('master.grd','aligned.grd')),('nointerp',['-nointerp'],('master.PRM','aligned.PRM')),
    ('norange',['-norange'],('master.PRM','aligned.PRM')),('interp8',['-interp','8'],('master.PRM','aligned.PRM')),
    ('range4',['-range_interp','4'],('master.PRM','aligned.PRM')),('noshift',['-noshift'],('master.PRM','aligned.PRM'))]
for name,opts,inputs in (modes if a.phase!='workflows' else []):
    ref=run(name+'_stock',options=opts,inputs=inputs)
    run(name+'_original_entry',mode='cli',options=opts,inputs=inputs,expected=ref)
    for workers in [1,3]:
        out=run(name+'_mt'+str(workers),backend='mt',mode='cli',options=[*opts,'-nproc',str(workers)],inputs=inputs,
                expected=None if name=='nointerp' else ref)
    if name not in ('time','time4','real','grid'):
        cc=run(name+'_cc_direct',backend='cc',options=[x for x in opts if x!='-freq'])
        run(name+'_cc_entry',backend='cc',mode='cli',options=opts,expected=cc)

if a.phase=='workflows':
    run('frequency_stock')
    run('frequency_cc_direct',backend='cc')
for backend in (executables if a.phase!='modes' else []):
    ref=root/('frequency_cc_direct' if backend=='cc' else 'frequency_stock')/'freq_xcorr.dat'
    for mode in ('config','workflow'):
        run(backend+'_'+mode,backend=backend,mode=mode,workers=3,expected=ref)
    if backend!='original':
        for mode in ('cli','config','workflow'):
            run(backend+'_write_failure_'+mode,backend=backend,mode=mode,workers=3,error=True,limit=128)
        run(backend+'_ignored_child_failure',backend=backend,mode='workflow',workers=3,error=True,
            inputs=('missing.PRM','aligned.PRM'),ignore_failure=True)

if a.phase!='modes':
    run('cc_geocode_missing_trans',backend='cc',mode='workflow',options=['-geocode'],error=True)
assert all(r['pass'] for r in records),[r['name'] for r in records if not r['pass']]
print('ALL PASS',len(records),flush=True)
